In [178]:
#Mohammad Amer Khalil
#+963935718668

#1. فهم البيانات

In [179]:
import pandas as pd
df = pd.read_csv('online_retail_task2_students.csv')

In [180]:
print (df.head())

  InvoiceNo StockCode                     Description  Quantity  \
0    536365    84029E  RED WOOLLY HOTTIE WHITE HEART.         6
1    536366     22633          HAND WARMER UNION JACK         6
2    536382     21832            CHOCOLATE CALCULATOR        12
3    536390     22968      ROSE COTTAGE KEEPSAKE BOX          8
4    536390    84030E   ENGLISH ROSE HOT WATER BOTTLE        24

           InvoiceDate  UnitPrice  CustomerID         Country
0  2010-12-01 08:26:00       3.39     17850.0  United Kingdom
1  2010-12-01 08:28:00       1.85     17850.0  United Kingdom
2  2010-12-01 09:45:00       1.65     16098.0  United Kingdom
3  2010-12-01 10:19:00       8.50     17511.0  United Kingdom
4  2010-12-01 10:19:00       3.75     17511.0  United Kingdom

In [181]:
print(f'Total rows: {len(df)}')

Total rows: 20000

In [182]:
print(f'Total columns: {len(df.columns)}')
print(f'Columns Names: {df.columns}')

Total columns: 8
Columns Names: Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [183]:
print('Data types:')
df.info()

Data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    20000 non-null  object
 1   StockCode    20000 non-null  object
 2   Description  19950 non-null  object
 3   Quantity     20000 non-null  int64
 4   InvoiceDate  20000 non-null  object
 5   UnitPrice    20000 non-null  float64
 6   CustomerID   14851 non-null  float64
 7   Country      20000 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.2+ MB

**Each row represnt an entry in a table of invoices so each row is one invoice**

**We can use StockCode, Description, Quantity, InvoiceDate, UnitPrice, Country in the analaysis**

**Based on the available columns we can infer the data is related to an online retail store**

**Where every row represents a purchase(InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country)**

**The goal of studying this data is to understand the customers behaviour, calcuate profits and determine the best selling products**

#2. فحص جودة البيانات

In [184]:
#we check for missing and duplicate values since they create an issue in analyzing the data
#missing values means no data to do analaysis on and duplicate means inaccurate analysis
print('Missing Values:')
print(df.isnull().sum())

Missing Values:
InvoiceNo         0
StockCode         0
Description      50
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID     5149
Country           0
dtype: int64

In [185]:
print(f"Number of duplicate rows: {df.duplicated().sum()}")
print(df.duplicated())

Number of duplicate rows: 8
0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Length: 20000, dtype: bool

In [186]:
# Summary statistics for numerical columns
display(df.describe())

           Quantity     UnitPrice    CustomerID
count  20000.000000  20000.000000  14851.000000
mean       9.511300      4.463227  15295.116692
std       39.946439    116.847348   1716.889608
min    -1296.000000 -11062.060000  12347.000000
25%        1.000000      1.250000  13950.000000
50%        3.000000      2.100000  15184.000000
75%       10.000000      4.130000  16805.000000
max     2400.000000   8142.750000  18283.000000

In [187]:
# Checking for nonsensical data values
print(f"Current number of rows with Quantity <= 0: {df[df['Quantity'] <= 0].shape[0]}")
print(f"Current number of rows with UnitPrice <= 0: {df[df['UnitPrice'] <= 0].shape[0]}")
#if the quantity was zero or less, or the Unitprice was zero or less it means the whole row is unusable for analysis

Current number of rows with Quantity <= 0: 365
Current number of rows with UnitPrice <= 0: 91

In [188]:
#checking for issues in datatypes
print(df.head())
print(df_clean.info())
#we can see several types can be changed for better processing later
#InvoiceData is object instead of date
#customerid is float but a more optimized version would be integer
#country object-> string, inovice number object -> integer, stock code object ->string
#Description object -> string object -> datetime

  InvoiceNo StockCode                     Description  Quantity  \
0    536365    84029E  RED WOOLLY HOTTIE WHITE HEART.         6
1    536366     22633          HAND WARMER UNION JACK         6
2    536382     21832            CHOCOLATE CALCULATOR        12
3    536390     22968      ROSE COTTAGE KEEPSAKE BOX          8
4    536390    84030E   ENGLISH ROSE HOT WATER BOTTLE        24

           InvoiceDate  UnitPrice  CustomerID         Country
0  2010-12-01 08:26:00       3.39     17850.0  United Kingdom
1  2010-12-01 08:28:00       1.85     17850.0  United Kingdom
2  2010-12-01 09:45:00       1.65     16098.0  United Kingdom
3  2010-12-01 10:19:00       8.50     17511.0  United Kingdom
4  2010-12-01 10:19:00       3.75     17511.0  United Kingdom
<class 'pandas.core.frame.DataFrame'>
Index: 14526 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    14526 non-null  object
 1   StockCode    14526 non-null  object
 2   Description  14526 non-null  object
 3   Quantity     14526 non-null  int64
 4   InvoiceDate  14526 non-null  datetime64[ns]
 5   UnitPrice    14526 non-null  float64
 6   CustomerID   14526 non-null  Int64
 7   Country      14526 non-null  category
 8   TotalAmount  14526 non-null  float64
 9   YearMonth    14526 non-null  period[M]
dtypes: Int64(1), category(1), datetime64[ns](1), float64(2), int64(1), object(3), period[M](1)
memory usage: 1.1+ MB
None

In [189]:
#checking for unexpected values and outliers that can create bias in the data analysis later
display(df[['Quantity', 'UnitPrice']].describe())
print("\nObservations on potential outliers and unexpected values:")
print(f"The max for quantity {df['Quantity'].max()}.")
print(f"The max UnitPrice {df['UnitPrice'].max()}.")
# for quantity since the 75th percentile is only 10, this is a clear outlier.
# for price it is also an outlier compared to the average price.

           Quantity     UnitPrice
count  20000.000000  20000.000000
mean       9.511300      4.463227
std       39.946439    116.847348
min    -1296.000000 -11062.060000
25%        1.000000      1.250000
50%        3.000000      2.100000
75%       10.000000      4.130000
max     2400.000000   8142.750000

Observations on potential outliers and unexpected values:
The max for quantity 2400.
The max UnitPrice 8142.75.

#3. التعامل مع المشاكل

In [190]:
import pandas as pd

# first lets drop the duplicates values,
df_clean = df.drop_duplicates()
# then lets also drop null values for both description and customerID
df_clean = df_clean.dropna(subset=['Description'])
df_clean = df_clean.dropna(subset=['CustomerID'])

print("Data Types Check (After Cleaning)")
df_clean.info()
#in a case of null or duplicate dropping the whole row is the best solution in this case where i can't fill the
# data myself and i can't work on empty data

Data Types Check (After Cleaning)
<class 'pandas.core.frame.DataFrame'>
Index: 14843 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    14843 non-null  object
 1   StockCode    14843 non-null  object
 2   Description  14843 non-null  object
 3   Quantity     14843 non-null  int64
 4   InvoiceDate  14843 non-null  object
 5   UnitPrice    14843 non-null  float64
 6   CustomerID   14843 non-null  float64
 7   Country      14843 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.0+ MB

In [191]:
# To solve the non-sensical values in quantity and unit price (less or equal to 0)
# We will filter out those rows because these values are illogical for sales and would skew any analysis(avareg quantity or total sales)
df_clean = df_clean[(df_clean['Quantity'] > 0) & (df_clean['UnitPrice'] > 0)].copy()

# Correcting data types as to match thier description by converting them
# Enabling proper time-series analysis, allowing for insights into sales trends over time.
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])

# Improving memory efficiency and ensures the ID is treated as a discrete numerical identifier, and to do grouping or filtering operations
df_clean['CustomerID'] = df_clean['CustomerID'].astype(pd.Int64Dtype())
df_clean['Country'] = df_clean['Country'].astype('category')

print("check after treating datatypes and nonsensical values")
df_clean.info()
print(f"Current number of rows with Quantity <= 0: {df_clean[df_clean['Quantity'] <= 0].shape[0]}")
print(f"Current number of rows with UnitPrice <= 0: {df_clean[df_clean['UnitPrice'] <= 0].shape[0]}")


# While the problem of extreme values (outliers) still exist for Quantity and Unitprice
# We have chosen to not take action like capping or removing since removing all of them without understanding of the context might
# ene up eliminating actually valueable information like bulk orders or high-value orders

display(df_clean[['Quantity', 'UnitPrice']].describe())
print(f"1. **'Quantity'**: The maximum quantity is {df_clean['Quantity'].max()}")
print(f"2. **'UnitPrice'**: The maximum unit price is {df_clean['UnitPrice'].max()}")

# Update the main df for use in other cells
df = df_clean

check after treating datatypes and nonsensical values
<class 'pandas.core.frame.DataFrame'>
Index: 14526 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    14526 non-null  object
 1   StockCode    14526 non-null  object
 2   Description  14526 non-null  object
 3   Quantity     14526 non-null  int64
 4   InvoiceDate  14526 non-null  datetime64[ns]
 5   UnitPrice    14526 non-null  float64
 6   CustomerID   14526 non-null  Int64
 7   Country      14526 non-null  category
dtypes: Int64(1), category(1), datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 937.6+ KB
Current number of rows with Quantity <= 0: 0
Current number of rows with UnitPrice <= 0: 0

           Quantity     UnitPrice
count  14526.000000  14526.000000
mean      12.247281      2.998048
std       43.218285      5.628479
min        1.000000      0.040000
25%        2.000000      1.250000
50%        5.000000      1.950000
75%       12.000000      3.750000
max     2400.000000    300.000000

1. **'Quantity'**: The maximum quantity is 2400
2. **'UnitPrice'**: The maximum unit price is 300.0

#4. إنشاء معلومات جديدة مفيدة

In [192]:

# Since there is no Total Amount I have chosen to create that by aggerating both Quantity and UnitPrice
# This column is useful for further analysis and calculations on revenue and profit
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']
df['YearMonth'] = df['InvoiceDate'].dt.to_period('M') # For monthly aggregation and trend analysis

In [193]:
display(df_clean[['Quantity', 'UnitPrice', 'TotalAmount','YearMonth']].describe())

           Quantity     UnitPrice   TotalAmount
count  14526.000000  14526.000000  14526.000000
mean      12.247281      2.998048     20.424143
std       43.218285      5.628479     61.422612
min        1.000000      0.040000      0.120000
25%        2.000000      1.250000      4.560000
50%        5.000000      1.950000     11.800000
75%       12.000000      3.750000     19.500000
max     2400.000000    300.000000   3035.520000

#5. التحقق من البيانات بعد التنظيف

In [194]:
import pandas as pd

df.info()
print("\nObservations on data types: All identified data type issues have been resolved. 'InvoiceDate' is now datetime, 'CustomerID' is a nullable integer (Int64Dtype), and 'Country' is a categorical type. New features ('TotalAmount', 'YearMonth') have also been successfully added.")

print(df.isnull().sum())
print("No missing values remain in 'Description' or 'CustomerID'.")

print(f"Number of duplicate rows: {df.duplicated().sum()}")
print("Duplicate rows have been successfully removed.")

print(df.isnull().sum())
print('All null values have been removed')

print(f"Current number of rows with Quantity <= 0: {df[df['Quantity'] <= 0].shape[0]}")
print(f"Current number of rows with UnitPrice <= 0: {df[df['UnitPrice'] <= 0].shape[0]}")
print("Observations: All non-positive quantities and unit prices have been removed.")

<class 'pandas.core.frame.DataFrame'>
Index: 14526 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    14526 non-null  object
 1   StockCode    14526 non-null  object
 2   Description  14526 non-null  object
 3   Quantity     14526 non-null  int64
 4   InvoiceDate  14526 non-null  datetime64[ns]
 5   UnitPrice    14526 non-null  float64
 6   CustomerID   14526 non-null  Int64
 7   Country      14526 non-null  category
 8   TotalAmount  14526 non-null  float64
 9   YearMonth    14526 non-null  period[M]
dtypes: Int64(1), category(1), datetime64[ns](1), float64(2), int64(1), object(3), period[M](1)
memory usage: 1.1+ MB

Observations on data types: All identified data type issues have been resolved. 'InvoiceDate' is now datetime, 'CustomerID' is a nullable integer (Int64Dtype), and 'Country' is a categorical type. New features ('TotalAmount', 'YearMonth') have also been successfully added.
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalAmount    0
YearMonth      0
dtype: int64
No missing values remain in 'Description' or 'CustomerID'.
Number of duplicate rows: 0
Duplicate rows have been successfully removed.
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalAmount    0
YearMonth      0
dtype: int64
All null values have been removed
Current number of rows with Quantity <= 0: 0
Current number of rows with UnitPrice <= 0: 0
Observations: All non-positive quantities and unit prices have been removed.

#6. ملخص جودة البيانات

After going through the whole process of cleaning the data:



*   Biggest problems I've faced were:
Duplicate and Null values, incorrect data types, non-sensical and outliers value and finally not enough columns to start the analysis process
*   I chose to to deal with these issues by removing duplicate and null values, to convert the columns with incorrect data types to thier suitable data types and to fix and remove rows that have non-sensical values, when it comes to the outliers i chose to keep them for now until further context is given so I can decide how will i handle them



*   dropping missing and dulicates was done because they cant be filled without deep field knoweledge, and data types were correct to enable optimized analysis, non-sensical values were filtered out to ensure all data repsernts real and logical sale transactions

*   What Changed in the Data After Cleaning? Number of rows were reduced, data types were corrected and new features `TotalAmount` and `YearMonth` were created to enrich the data and provide deeper analytical insights

*  Data is reaedy for analaysis since now it's clean, consistent, and enriched with new features. Making it suitable for more analytical studies since all basic data quality issues have been successfully addressed.

In [195]:
#exporting processed data
df.to_csv('online_retail_task2_students_processed.csv', index=False)